### ISSUE TITLE
Write Makefile for Swagger 

### ISSUE THREAD

**Issue by spathan1985** [cloudmesh-community/hid-sp18-516#17]
* [x] Write a Makefile to generate the swagger code, run the service, test the service
* [x] test the Makefile

**Comment by spathan1985** [comment]
Have written the initial version and uploaded on github on March 3rd.
All targets work except for 'clean'. Have asked Tyler for help on this issue.

**Comment by spathan1985** [comment]
It would be great if the TA's or the instructor can take a look at the Makefile and suggest if improvements are needed.

**Comment by laszewsk** [comment]
this should be read from ~/.cloudmesh/security.yaml 
Basic YWRtaW46c2VjcmV0

YOu still have server code in the dir, i suggest you remove all of this ONCE YOU CREATE A BACKUP and remove the swagger code dir. THis way your dir is real clean.

**Comment by laszewsk** [comment]
rename cloudmesh/swagger_assignment, we may have to rename it a second time, but this way it would be easier for us to find with our scripts

**Comment by laszewsk** [comment]
clean would simply remove the dir of teh server code

**Comment by spathan1985** [comment]
Thanks for your comments Professor. I will do that. So all the yaml and controller files would be under ~/cloudmesh/swagger directory or just ~/cloudmesh directory?

**Comment by laszewsk** [comment]
better would be just swagger in github

within that dir you just have Makefile and controller.py files and README.md on how to create the code. So all other dirs are creaed frm the makefile

**Comment by spathan1985** [comment]
Submitted the Makefile and incorporated all the changes suggested by Professor.
Hence closing this issue.
