### ISSUE TITLE
openstack cluster

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh-community/hid-sp18-516#23]
1. citations can not be at beginning of sentence
2. are you quoting correctly?
3. it woudl be cool if you can add a section that shows how to set this up also in a container with a docker file and than show how to interactively log into the container and use it. you make have to place the openrc file somewhere and mount on container start up

**Comment by spathan1985** [comment]
@laszewsk Professor, I saw this post only yesterday.
I have added the Dockerfile and corrected the citation issue as well.
Thanks for your feedback.
