### ISSUE TITLE
some routes are non nouns

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh-community/hid-sp18-516#5]

**Comment by spathan1985** [comment]
What is this about Professor? I did not get this. Could you please explain?

**Comment by laszewsk** [comment]
you us get in your routs, but routes must be nouns

**Comment by spathan1985** [comment]
Oh Ok. I will correct this soon, thank you.

**Comment by spathan1985** [comment]
Hello Professor, 
I have corrected the routes as nouns.
Nice to get this feedback, please let me know if you find anything else not correct.
Thank you.
